spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/payment
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  #spring cloud
  cloud:
    stream:
      kafka:
        binder:
          brokers: pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username='7XMRAGCB5H3YKHOL' password='qHvJWkiFHEt9QYjTOctPfduEOupknS2ohtv9o7EpeXFe883cjec4EvdI+uxocAQ7';
              mechanism: PLAIN
            client:
              id: ccloud-springboot-client-ba5bacc8-54fe-4034-b306-d22c49e172ff
              dns:
                lookup: use_all_dns_ips
          required-acks: all
          auto-create-topics: false

        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

          wallet-in-0:
            consumer:
              configuration:
                isolation:
                  level: read_committed
              enable-dlq: true
              dlq-name: wallet_payment_dlq

          ledger-in-0:
            consumer:
              configuration:
                isolation:
                  level: read_committed
              enable-dlq: true
              dlq-name: ledger_payment_dlq

      bindings:
        consume-in-0:
          destination: payment
          group: payment-service

        send-out-0:
          destination: payment-result
          group: payment-service
          producer:
            record-metadata-channel: payment-result

        wallet-in-0:
          destination: wallet
          group: payment-service

        ledger-in-0:
          destination: ledger
          group: payment-service

        payment-result:
          destination: payment-result-metadata

    function:
      definition: send;wallet;ledger

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

feign:
  client:
    config:
      tossPaymentClient:
        url: https://api.tosspayments.com


management:
  endpoints:
    web:
      exposure:
        include: bindings

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug            # 실행된 SQL
    org.hibernate.type.descriptor.sql: trace  # 바인딩된 파라미터
