spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/payment
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: pkc-e82om.ap-northeast-2.aws.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username='SWJHFI3EMFCYBGO7' password='7X/bhgJpXB1h2x0H9JTKhBWVz4RNzScRASwjb2dkB5EjrV/P8e9aiRDRxcSAUL5T';
              mechanism: PLAIN
            client:
              dns:
                lookup: use_all_dns_ips

          required-acks: all
          auto-create-topics: false

        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

          wallet-in-0:
            consumer:
              configuration:
                isolation:
                  level: read_committed
              enable-dlq: true
              dlq-name: wallet_payment_dlq

          ledger-in-0:
            consumer:
              configuration:
                isolation:
                  level: read_committed
              enable-dlq: true
              dlq-name: ledger_payment_dlq

      bindings:
        send-out-0:
          destination: payment
          group: payment-service

        wallet-in-0:
          destination: wallet
          group: payment-service

        ledger-in-0:
          destination: ledger
          group: payment-service

#        send-in-0:
#          destination: dummy
#          group: payment-service

    function:
      definition: send;wallet;ledger

PSP:
  toss:
    url: https://api.tosspayments.com
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

feign:
  client:
    config:
      tossPaymentClient:
        url: https://api.tosspayments.com

management:
  endpoints:
    web:
      exposure:
        include: bindings

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
